facts
 357     
2       0       0       1       0       37       [  low  female  PrimD25  Admit3
60      
 1143    
5       1       0       0       0       1        [  unknown  male  PrimD15  Admit4
7       
 2095    
1       1       0       0       0       30       [  unknown  male  PrimD31  Admit5
14      
 2636    
2       0       0       1       0       22       [  low  male  PrimD32  Admit4
123     
 3425    
2       0       1       0       0       26       [  unknown  male  PrimD22  Admit1
80      
 4617    
2       0       1       0       0       30       [  low  male  PrimD22  Admit4
22      
