facts
 2554    
2       1       0       0       0       8        [  unknown  female  PrimD22  Admit4
55      
 195     
5       0       1       0       1       18       [  high  male  PrimD32  Admit4
182     
 8374    
7       0       0       1       0       64       [  unknown  female  PrimD27  Admit4
93      
 5647    
2       1       0       0       1       15       [  unknown  male  PrimD12  Admit4
14      
 3224    
5       0       1       0       0       11       [  unknown  male  PrimD25  Admit4
30      
 1026    
1       1       0       0       0       8        [  unknown  female  PrimD1  Admit4
7       
